# STEP 1: Compilación del código de React
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL
RUN npm run build

# STEP 2: Servidor de producción Nginx
FROM nginx:alpine as runner

# 2. Copiamos los archivos compilados de React (Vite los genera en /dist)
COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]